### PR TITLE
Add graphql sample backend

### PR DESCRIPTION
**Pull request by RakhithaRR**
## Purpose
This PR adds a sample Star Wars backend server which can be used to demonstrate the GraphQL scenarios in APIM.

Related issue: https://github.com/wso2/docs-apim/issues/1909

### CODE REVIEW

**Review by HiranyaKavishani — APPROVED** [review]

**Comment by HiranyaKavishani** [comment]
@RakhithaRR Could you please add graphQL schema to here?

**Comment by RakhithaRR** [comment]
Schema is included in the `swapiSchema.js` file.

**Comment by fazlan-nazeem** [comment]
@RakhithaRR better to the schema file to this as a separate file with a .graphql extension.

**Review by fazlan-nazeem — APPROVED** [review]

**Comment by RakhithaRR** [comment]
@HiranyaKavishani @fazlan-nazeem added the schema with ecf7dc3

**Pull request merged**
